export default {
  settings: {
    updateFolios: true,
  },
  fields: [
    {
      id: 1,
      key: 'id',
      label: 'Id',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 2,
      key: 'properties',
      label: 'Folios in DB',
      multiple: true,
      multiple_settings: {
        id: 'folio',
        value: 'folio',
      },
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 3,
      key: 'working_properties',
      label: 'Wrong Folios',
      multiple: true,
      multiple_settings: {
        id: 'folio',
        value: 'folio',
      },
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 4,
      key: 'case_number',
      label: 'Case Number',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 5,
      key: 'date_filed',
      label: 'Date Filed',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: true,
    },
    {
      id: 6,
      key: 'relationship',
      label: 'Relationship',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 7,
      key: 'administrator',
      label: 'Administrator',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 8,
      key: 'petitioner',
      label: 'Petitioner',
      sortable: true,
      multiple: false,
      visible: false,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 9,
      key: 'deceased',
      label: 'Deceased',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 10,
      key: 'fips',
      label: 'FIPS',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 11,
      key: 'reason',
      label: 'Reason',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 12,
      key: 'item_example',
      label: 'Sample',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: false,
    },
    {
      id: 13,
      key: 'tag',
      label: 'Tag',
      multiple: false,
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 14,
      key: 'observations',
      label: 'Observations',
      multiple: false,
      visible: true,
      active: true,
      update: true,
    },
    {
      id: 15,
      key: 'latest_modification_date',
      label: 'Latest Modification Date',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 16,
      key: 'created_date',
      label: 'Created Date',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: true,
    },
    {
      id: 17,
      key: 'actions',
      label: '',
      multiple: false,
      visible: false,
      active: true,
      update: false,
    },
  ],
}
