export default [
  {
    id: 1,
    key: 'probate_id',
    label: 'Probate Id',
    multiple: false,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'folio_db',
    label: 'BD Folios',
    multiple: true,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'folio_file',
    label: 'File Folios',
    multiple: true,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 3,
    key: 'case_number',
    label: 'Case Number',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 4,
    key: 'date_filed',
    label: 'Date Filed',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 5,
    key: 'relationship',
    label: 'Relationship',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 6,
    key: 'administrator',
    label: 'Administrator',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 7,
    key: 'petitioner',
    label: 'Petitioner',
    multiple: false,
    visible: false,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 8,
    key: 'deceased',
    label: 'Deceased',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 9,
    key: 'fips',
    label: 'FIPS',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 10,
    key: 'actions',
    label: 'Actions',
    multiple: false,
    visible: false,
    active: true,
    update: false,
  },
]
