export default [
  {
    id: 1,
    key: 'id',
    label: 'Id',
    multiple: false,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'properties',
    label: 'Folios in DB',
    multiple: true,
    multiple_settings: {
      id: 'folio',
      value: 'folio',
    },
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 3,
    key: 'working_properties',
    label: 'Wrong Folios',
    multiple: true,
    multiple_settings: {
      id: 'folio',
      value: 'folio',
    },
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 4,
    key: 'case_number',
    label: 'Case Number',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
    date: false,
  },
  {
    id: 5,
    key: 'date_filed',
    label: 'Date Filed',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
    date: true,
  },
  {
    id: 6,
    key: 'relationship',
    label: 'Relationship',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
    date: false,
  },
  {
    id: 7,
    key: 'administrator',
    label: 'Administrator',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
    date: false,
  },
  {
    id: 8,
    key: 'petitioner',
    label: 'Petitioner',
    multiple: false,
    visible: false,
    active: false,
    update: true,
    select: false,
    date: false,
  },
  {
    id: 9,
    key: 'deceased',
    label: 'Deceased',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
    date: false,
  },
  {
    id: 10,
    key: 'fips',
    label: 'FIPS',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
    date: false,
  },
  {
    id: 11,
    key: 'reason',
    label: 'Reason',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
    date: false,
  },
  {
    id: 12,
    key: 'item_example',
    label: 'Sample',
    multiple: false,
    visible: true,
    active: false,
    update: false,
    date: false,
  },
  {
    id: 13,
    key: 'actions',
    label: 'Actions',
    multiple: false,
    visible: false,
    active: true,
    update: false,
  },
]
