export default [
  {
    id: 1,
    folio: 2834892,
    address: '9901 Nw 33Rd Ave',
    city: 'Miami',
    country: 'Miami Dade',
    zip: '238-234',
    property_type: 'SingleFamily',
    people: [
      {
        prospect: 'Jorge Unzueta',
        phoneNumber: 12345,
        campaigns: 5,
        verified: true,
        prospectStatus: "Don't call",
        leadStage: 'Dead',
        lastContact: '05/08/2019',
      },
      {
        prospect: 'Sara Unzueta',
        phoneNumber: 123425,
        campaigns: 4,
        verified: true,
        prospectStatus: "Don't call",
        leadStage: 'Dead',
        lastContact: '05/08/2019',
      },
    ],
  },
  {
    id: 2,
    folio: 2834892,
    address: '9901 Nw 33Rd Ave',
    city: 'Miami',
    country: 'Miami Dade',
    zip: '238-234',
    property_type: 'SingleFamily',
    people: [
      {
        prospect: 'Joel Unzueta',
        phoneNumber: 12345,
        campaigns: 5,
        verified: true,
        prospectStatus: "Don't call",
        leadStage: 'Dead',
        lastContact: '05/08/2019',
      },
      {
        prospect: 'Rico Unzueta',
        phoneNumber: 123425,
        campaigns: 4,
        verified: true,
        prospectStatus: "Don't call",
        leadStage: 'Dead',
        lastContact: '05/08/2019',
      },
    ],
  },
]
