export default [
  {
    id: 1,
    key: 'foreclosure_id',
    label: 'Foreclosure Id',
    multiple: false,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'folio_db',
    label: 'BD Folios',
    multiple: true,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'folio_file',
    label: 'File Folios',
    multiple: true,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 3,
    key: 'cfn',
    label: 'CFN',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 4,
    key: 'date_filed',
    label: 'Date Filed',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 5,
    key: 'sale_date',
    label: 'Sale Date',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 6,
    key: 'add_date',
    label: 'Add Date',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 7,
    key: 'Auction_status',
    label: 'Auction Status',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: true,
    options: [
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
    ],
  },
  {
    id: 8,
    key: 'final_judgement',
    label: 'Final Judgement',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 9,
    key: 'assessed_value',
    label: 'Assessed Value',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 10,
    key: 'petitioner',
    label: 'Petitioner',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 11,
    key: 'property_owner',
    label: 'Property Owner',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 12,
    key: 'plaintiff',
    label: 'Plaintiff',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 13,
    key: 'certificate_holder_name',
    label: 'Certificate Holder Name',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 14,
    key: 'fips',
    label: 'FIPS',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 15,
    key: 'actions',
    label: 'Actions',
    multiple: false,
    visible: false,
    active: true,
    update: false,
  },
]
