export default [
  {
    id: 1,
    key: 'id',
    label: 'Id',
    multiple: false,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'properties',
    label: 'Folios in DB',
    multiple: true,
    multiple_settings: {
      id: 'folio',
      value: 'folio',
    },
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 3,
    key: 'working_properties',
    label: 'Wrong Folios',
    multiple: true,
    multiple_settings: {
      id: 'folio',
      value: 'folio',
    },
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 4,
    key: 'case_number',
    label: 'Case Number',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 5,
    key: 'date_filed',
    label: 'Date Filed',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 6,
    key: 'type',
    label: 'Type',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: true,
    options: [
      { label: 'Residential', value: 'RESIDENTIAL' },
      { label: 'Non Residential', value: 'NON-RESIDENTIAL' },
    ],
  },
  {
    id: 7,
    key: 'property_owner',
    label: 'Property Owner',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 8,
    key: 'petitioner',
    label: 'Petitioner',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 9,
    key: 'fips',
    label: 'FIPS',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 9,
    key: 'tag',
    label: 'Tag',
    multiple: false,
    visible: true,
    active: false,
    update: false,
    select: false,
  },
  {
    id: 10,
    key: 'item_example',
    label: 'Sample',
    multiple: false,
    visible: true,
    active: false,
    update: false,
  },
  {
    id: 11,
    key: 'actions',
    label: '',
    multiple: false,
    visible: true,
    active: true,
    update: false,
  },
]
