export default {
  settings: {
    updateFolios: false,
  },
  fields: [
    {
      id: 1,
      key: 'id',
      label: 'Id',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 2,
      key: 'properties',
      label: 'Folios in DB',
      multiple: true,
      multiple_settings: {
        id: 'folio',
        value: 'folio',
      },
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 3,
      key: 'working_properties',
      label: 'Wrong Folios',
      multiple: true,
      multiple_settings: {
        id: 'folio',
        value: 'folio',
      },
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 4,
      key: 'folio',
      label: 'Folio',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
      folio: true,
    },
    {
      id: 5,
      key: 'earliest_yr',
      label: 'Earliest Year',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 6,
      key: 'latest_yr',
      label: 'Latest Year',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 7,
      key: 'account_status',
      label: 'Account Status',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 8,
      key: 'cert_status',
      label: 'Cert Status',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 9,
      key: 'deed_status',
      label: 'Deed Status',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 10,
      key: 'owner_name',
      label: 'Owner Name',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 11,
      key: 'count_tax_year',
      label: 'Count Tax Year',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 12,
      key: 'sum_amount',
      label: 'Sum Amount',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 13,
      key: 'fips',
      label: 'FIPS',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 14,
      key: 'homestead',
      label: 'Homestead',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 15,
      key: 'reason',
      label: 'Reason',
      sortable: true,
      multiple: false,
      visible: true,
      active: false,
      update: true,
      select: false,
      date: false,
    },
    {
      id: 16,
      key: 'tag',
      label: 'Tag',
      multiple: false,
      visible: true,
      active: true,
      update: false,
    },
    {
      id: 18,
      key: 'observations',
      label: 'Observations',
      multiple: false,
      visible: true,
      active: true,
      update: true,
    },
    {
      id: 19,
      key: 'latest_modification_date',
      label: 'Latest Modification Date',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: false,
      date: true,
    },
    {
      id: 20,
      key: 'created_date',
      label: 'Created Date',
      sortable: true,
      multiple: false,
      visible: true,
      active: true,
      update: true,
      select: false,
      date: true,
    },
    {
      id: 21,
      key: 'actions',
      label: '',
      multiple: false,
      visible: false,
      active: true,
      update: false,
    },
  ],
}
