export default [
  {
    id: 1,
    key: 'tax_delinquency_id',
    label: 'Tax Delinquency Id',
    multiple: false,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'folio_db',
    label: 'BD Folios',
    multiple: true,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 2,
    key: 'folio_file',
    label: 'File Folios',
    multiple: true,
    visible: true,
    active: true,
    update: false,
  },
  {
    id: 3,
    key: 'earliest_yr',
    label: 'Earliest Year',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 4,
    key: 'account_status',
    label: 'Account Status',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: true,
    options: [
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
    ],
  },
  {
    id: 5,
    key: 'cert_status',
    label: 'Cert Status',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: true,
    options: [
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
    ],
  },
  {
    id: 6,
    key: 'deed_status',
    label: 'Deed Status',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: true,
    options: [
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
    ],
  },
  {
    id: 7,
    key: 'owner_name',
    label: 'Owner Name',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 8,
    key: 'count_tax_year',
    label: 'Count Tax Year',
    multiple: false,
    visible: true,
    active: false,
    update: true,
  },
  {
    id: 9,
    key: 'sum_amount',
    label: 'Sum Amount',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 10,
    key: 'fips',
    label: 'FIPS',
    multiple: false,
    visible: true,
    active: true,
    update: true,
    select: false,
  },
  {
    id: 11,
    key: 'homestead',
    label: 'Homestead',
    multiple: false,
    visible: true,
    active: false,
    update: true,
    select: false,
  },
  {
    id: 12,
    key: 'actions',
    label: 'Actions',
    multiple: false,
    visible: false,
    active: true,
    update: false,
  },
]
